server:
  port: 8888

#db related configuration    
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager
    
#jpa or hibernate related config    
  jpa:
   # show-sql: true
    #hibernate:
     #ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        #format_sql: true
        
# email confiuration       
  mail:
    host: smtp.gmail.com
    port: 587
    username: saumyaranjanm56@gmail.com
    password: saumya
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true      
                       
